services:
  - type: web
    name: trisha-gemini-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: GEMINI_API_KEY
        fromDatabase: true
